language: cpp

services:
  - docker

sudo: required
dist: trusty
osx_image: xcode8.3

env:
  global:
    - QT_VER=5.9.1
    - PROJECT=QtRestClient
    - EXTRA_MODULES=.skycoder42.jsonserializer

matrix:
  include:
    - os: linux
      env:
        - PLATFORM=gcc_64
        - BUILD_DOC=true
    - os: linux
      env:
        - PLATFORM=android_armv7
    - os: linux
      env:
        - PLATFORM=android_x86
    - os: osx
      env:
        - PLATFORM=clang_64
    - os: osx
      env:
        - PLATFORM=ios

before_install:
  - git clone https://github.com/Skycoder42/QtModules.git ./qtmodules-travis
  - ./tests/ci/setup.sh
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then travis_wait 40 ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh; else ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh; fi

script:
  - ./tests/auto/restclient/rest-db-setup.sh &
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/build.sh

before_deploy:
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/upload-prepare.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: juYFBTtn/vpb/c4WthQIeAqWqeW0zrg2Sl7BeEj7Udi8NQoWafrMGq8xSGfodkbK1yugxGFYQ6u1UOKoK4M2JHuDzHnNCRBwgJ9X89RlmRISALUnTXQRketdyo2ydy89sVEdppG9v2eXyC4R599GmE/I49jLkXLvED1j8uSLhZNDR2OYUH+no0gpnULnbHCZtwBr4wRYi1tH0hPf3xeoDFX5Tgz4yVgyX9+paBJln+Ate5CzlGyuT8AD4Sw+zRAixh6uUlFj90cXIc/JzJkHvPRoHy73TwauFurq2CaPc+UyIgQhISUZyArFi/mMpc1FVkBrKrb5eu1FmUiOkQtbIiMW51yGD8bW+N10oR2TJQU1/tyk4TLGvSISAx5Op07Q665w/qIQsbV6TNZxsNarWFI1VgOn49NOglc8dxeYAoE1IGKc+fbupYgQUcDKfrOx0/kRmc2VkBmPANh4FNAkREBQkvFGoEmHvhuBMs/eCDYWz/mu3ORQqmWZK415JWukgwxeuz0c1GWEPSx8S+L20K+iCZH3+kByerFPDc5185V0M90o9DzK0UNXhH+TGfP4cozrv43L/tTRAwaJTyVguj6p/+CRwifpLVOashcmer6JkDXVPqf+q8z588LLWDTuficj4rY95Cd+WxqBy5j97//5L4ckYqkDfTB7vE4d5cI=
  file_glob: true
  file: install/opt/build_*_$QT_VER.tar.xz
  on:
    repo: Skycoder42/QtRestClient
    tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
